### ISSUE TITLE
How does the Authentication work?

### ISSUE THREAD

**Issue by chucklu** [skipmaple/github-daily#169]
https://github.com/skipmaple/github-daily/blob/main/utils/issue.js#L7
```js
 secrets = require('../secret.js')
```
where is the secret.js file?

https://github.com/skipmaple/github-daily/blob/main/utils/issue.js#L16
```js
 installationId: 33004089,
```
where can I find the installation id for my forked repository?

Are you using https://github.com/octokit/auth-app.js/#authenticate-as-installation?

**Comment by skipmaple** [comment]
`secret.js` file like this:

```js
const clientSecret = 'xxxxxxxxxxx'
const privateKey = '-----BEGIN RSA PRIVATE KEY-----\n' +
    'xxxxxxxxxxxxxxxxxxiTrZAaI3MN7Ml9Hm0xZ5/Xw49ytlWW2d8ySYJ+d9Uo6yzg\n' +
    'xxxxxxxxxxxxxxxxxxV7XTLEOZxmhlVDk+SC8Z17XzGWVqn75RkDcz/caHRf7kb3\n' +
    'awCuKn3Ge9QBPHcp/jHL7UqlJQt6t6so3xvB7lf73Lk5s/VW7NR0VSsVXYgFfyTs\n' +
    'yXgDdhFdZVAOzP4Agz3e5Sqzndevj2rrwurMm1r/PN53k0AQDRzycED4oU5hKD17\n' +
    'GI4D5yOBLTvbnEBnCc3m5KBktlpYwgIFEXtShUSwvodFE3azpzVIA3KHxd/IwwTD\n' +
    'cMgvskHmIlou3VxthnkyFE9Hd0Whr4K1SKOl4wIDAQABAoIBAE1gfi7tkv0Gy3eE\n' +
    'nggUpya2TcM3UmBhjM4QYKfdps8gemJlZBy6kSKPOa4zxqTQF4sM5RcdRqxIFAwi\n' +
    'bhMFbTadBf/S7SmTllkA66ER1rsM/mov5qZMD9uLHr5OKwLBrqK1Ocl+i+UGcFIL\n' +
    'E0y69Pbuf7yTFDiROSSajA5l3UB+NL3/mB3aUpwCNUd9QBUTRW21QdoL+VYjTbmg\n' +
    'Cdrf2xyIqYmbCkEyCyVXrB+q4CGb8WKOsoudhwtZy67AIdxpAn9Wtm14VFfTPabV\n' +
    'YxvMuwsiOCfcKf1FMzJ8hElIEX2xaovhYREsfdXdipzLEaZQNB0Gsqxa0qfb724X\n' +
    'AYKJVVkCgYEA9V2NwtSkdJZZP62FXv6FSXVhoCS34YeJ3bwyul7yZg6rd53XtMdm\n' +
    '4WKrx7ZtXChRK61ewwf7tKQZ0YC+VNR9PTpK2jUXGW7E/uW/N37n2k08c5Ltqs4+\n' +
    'dL5P6+50CVLrzuORrD4nuzMQr8tXIEiKqWsH9xhx5VBmbfAnaRurVI8CgYEAwDSY\n' +
    'soNHcyzwP3rHce5NURbuQ2O9JHJP1GbeLJVPLbuDWFGxHm+XCa0fRGGd0nazW6Rw\n' +
    'pyxQCC7zj7II6vt7CwGBrOKWBwaZYfzk5uBClt0OukXLhrVigBr6l/dhNxL1r148\n' +
    'kyIYdi+la40YG6KJx8dOrK9GZgFGpJVrR1NJi20CgYA3LJdhFVH5yYk+MXXJO7Cb\n' +
    'KSMP0NHsi/7rdpNtp0YYvvm9xyenRiOTUQ3Rter3izVdffnOH3BxWWlY2/twteuH\n' +
    'piEI2mFcXbU8oEsUXpwiUbXjQ0ngW8pdlCICqrc7FYNjHXc3ZS6oAL6i2TW5U7ai\n' +
    'jCfZX4zVBPRTimpCT2+CbwKBgQCbnboHxjxiJv85FipGtx8ISV2NWEJ6MMcrfEHj\n' +
    'rNuXdltIdZPGxahu4CkRj0tdbFeZGhFPeJQvm/v82rNXtVaQuZ6JIEdB1vj2me+m\n' +
    'cenYBZB4Bixbm53thGpiAZtHIOWkH9NBePh/L+JpqqnbLgUJp/et3pdL3TqZ5JQg\n' +
    'AnHoHQKBgQDX4ft4XV+MFJas8Ebcbd0j4lppe5+NSibmYwPpONye50NgqpuRQ+3u\n' +
    'uDTbL9TpRFdTHaJsvd6qptXkpFecDfDuikRHuRwyS7cx9JD0K/AREAAmb+BkEAVX\n' +
    'JdMqjTD9+quHMv8sDAadZQeUQPNuYYGLFTdEetpoaJDbOFDmXlPV+w==\n' +
    '-----END RSA PRIVATE KEY-----'

module.exports = {
    clientSecret,
    privateKey,
}
```

It only use for development environment, you can set github actions secrets to make it work. ref code: 

https://github.com/skipmaple/github-daily/blob/c7cf61c07de49107ec676a7ff585f298e3f9f7de/utils/issue.js#L18

**Comment by skipmaple** [comment]
> 
Create a github apps:
https://github.com/settings/apps
<img width="1352" alt="Screenshot 2023-06-13 at 17 03 12" src="https://github.com/skipmaple/github-daily/assets/49176897/9f5e276d-0c85-48d8-a9f8-9999b207cf4c">

reference_link: https://www.npmjs.com/package/octokit#authentication

**Comment by skipmaple** [comment]
> @skipmaple Thanks, but what's the installationId: 33004089? where can I find this for my project? https://github.com/skipmaple/github-daily/blob/main/utils/issue.js#L16

Actually I forgot how to create the installationid before, now I found this link, you can have a look:
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#generating-an-installation-access-token

**Comment by chucklu** [comment]
Finally I find the installation id in url, https://github.com/organizations/ChuckFork/settings/installations/ on this page, click the github app, and it will redirect to a new page, and the weird thing is the installation id only showed in url, not show as one property on page.

and for permission to lock the issue, we need enable the write access for issues on github apps created
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#issues
not sure why the created permission is enabled by default, when the issues permission is default as NoAccess

**Comment by chucklu** [comment]
> `secret.js` file like this:
> 
> ```js
> const clientSecret = 'xxxxxxxxxxx'
> const privateKey = '-----BEGIN RSA PRIVATE KEY-----\n' +
>     'xxxxxxxxxxxxxxxxxxiTrZAaI3MN7Ml9Hm0xZ5/Xw49ytlWW2d8ySYJ+d9Uo6yzg\n' +
>     'xxxxxxxxxxxxxxxxxxV7XTLEOZxmhlVDk+SC8Z17XzGWVqn75RkDcz/caHRf7kb3\n' +
>     'awCuKn3Ge9QBPHcp/jHL7UqlJQt6t6so3xvB7lf73Lk5s/VW7NR0VSsVXYgFfyTs\n' +
>     'yXgDdhFdZVAOzP4Agz3e5Sqzndevj2rrwurMm1r/PN53k0AQDRzycED4oU5hKD17\n' +
>     'GI4D5yOBLTvbnEBnCc3m5KBktlpYwgIFEXtShUSwvodFE3azpzVIA3KHxd/IwwTD\n' +
>     'cMgvskHmIlou3VxthnkyFE9Hd0Whr4K1SKOl4wIDAQABAoIBAE1gfi7tkv0Gy3eE\n' +
>     'nggUpya2TcM3UmBhjM4QYKfdps8gemJlZBy6kSKPOa4zxqTQF4sM5RcdRqxIFAwi\n' +
>     'bhMFbTadBf/S7SmTllkA66ER1rsM/mov5qZMD9uLHr5OKwLBrqK1Ocl+i+UGcFIL\n' +
>     'E0y69Pbuf7yTFDiROSSajA5l3UB+NL3/mB3aUpwCNUd9QBUTRW21QdoL+VYjTbmg\n' +
>     'Cdrf2xyIqYmbCkEyCyVXrB+q4CGb8WKOsoudhwtZy67AIdxpAn9Wtm14VFfTPabV\n' +
>     'YxvMuwsiOCfcKf1FMzJ8hElIEX2xaovhYREsfdXdipzLEaZQNB0Gsqxa0qfb724X\n' +
>     'AYKJVVkCgYEA9V2NwtSkdJZZP62FXv6FSXVhoCS34YeJ3bwyul7yZg6rd53XtMdm\n' +
>     '4WKrx7ZtXChRK61ewwf7tKQZ0YC+VNR9PTpK2jUXGW7E/uW/N37n2k08c5Ltqs4+\n' +
>     'dL5P6+50CVLrzuORrD4nuzMQr8tXIEiKqWsH9xhx5VBmbfAnaRurVI8CgYEAwDSY\n' +
>     'soNHcyzwP3rHce5NURbuQ2O9JHJP1GbeLJVPLbuDWFGxHm+XCa0fRGGd0nazW6Rw\n' +
>     'pyxQCC7zj7II6vt7CwGBrOKWBwaZYfzk5uBClt0OukXLhrVigBr6l/dhNxL1r148\n' +
>     'kyIYdi+la40YG6KJx8dOrK9GZgFGpJVrR1NJi20CgYA3LJdhFVH5yYk+MXXJO7Cb\n' +
>     'KSMP0NHsi/7rdpNtp0YYvvm9xyenRiOTUQ3Rter3izVdffnOH3BxWWlY2/twteuH\n' +
>     'piEI2mFcXbU8oEsUXpwiUbXjQ0ngW8pdlCICqrc7FYNjHXc3ZS6oAL6i2TW5U7ai\n' +
>     'jCfZX4zVBPRTimpCT2+CbwKBgQCbnboHxjxiJv85FipGtx8ISV2NWEJ6MMcrfEHj\n' +
>     'rNuXdltIdZPGxahu4CkRj0tdbFeZGhFPeJQvm/v82rNXtVaQuZ6JIEdB1vj2me+m\n' +
>     'cenYBZB4Bixbm53thGpiAZtHIOWkH9NBePh/L+JpqqnbLgUJp/et3pdL3TqZ5JQg\n' +
>     'AnHoHQKBgQDX4ft4XV+MFJas8Ebcbd0j4lppe5+NSibmYwPpONye50NgqpuRQ+3u\n' +
>     'uDTbL9TpRFdTHaJsvd6qptXkpFecDfDuikRHuRwyS7cx9JD0K/AREAAmb+BkEAVX\n' +
>     'JdMqjTD9+quHMv8sDAadZQeUQPNuYYGLFTdEetpoaJDbOFDmXlPV+w==\n' +
>     '-----END RSA PRIVATE KEY-----'
> 
> module.exports = {
>     clientSecret,
>     privateKey,
> }
> ```
> 
> It only use for development environment, you can set github actions secrets to make it work. ref code:
> 
> https://github.com/skipmaple/github-daily/blob/c7cf61c07de49107ec676a7ff585f298e3f9f7de/utils/issue.js#L18


Thanks for the tip, I did it like this, read content from file path
```js
const fs = require('fs');

const clientSecretPath = 'filepath'
const clientSecret = fs.readFileSync(clientSecretPath, 'utf8');

const privateKeyPath = 'file path';
const privateKey = fs.readFileSync(privateKeyPath, 'utf8');

module.exports = {
    clientSecret,
    privateKey,
}
```
